server:
  port: 8082

spring:
  application:
    name: chat-list-server

  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/

  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018/?replicaSet=rs0
      database: chatdb

  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux?useUnicode=true&characterEncoding=utf-8&serverZoneId=UTC
    username: java
    password: java
    properties:
      logging.level.org.springframework.r2dbc.core: DEBUG

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-room-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true

  redis:
    host: 127.0.0.1
    port: 6379
    repositories:
      enabled: false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8

jwt:
  secret: iOaMqTcUVTa0UuNTy4XfYrE9YJuWTUPg0QAWyZazn5iPdlP8GObBRAg4YgaLk2gHQ7DRf71AYj8bml0yhnZXwE9YJuWTUPg0QAWyZazn5iPdlP8GObNTy4XfYrE9YJuWTUPg0QAWyZa
  access-token-expiration: 1800000  # 30분
  refresh-token-expiration: 604800000  # 7일

logging:
  level:
    root: INFO